---
stages:
  build:
    buildTool: "mta"
    buildDescriptor: "mta.yaml"
    buildToolVersion: "MBTJ21N22"
  malwareScan:
    scan: false
  release:
    cloudTransportManagement:
      nodeOperation: "export"
      nodeName: "DEV"
      credential: "sue-ctms-service-key"
